version: 1
groups:
  - annotation: ckanext-datastore-search settings
    options:
      - key: ckanext.datastore_search.engine
        default: solr
        description: |
          Name of the engine to use.
        validators: ignore_missing
        required: false
      - key: ckanext.datastore_search.url
        default: None
        description: |
          The URL of the search engine.
        example: |
          http://solr-devm:8983
        required: true
      - key: ckanext.datastore_search.prefix
        default: datastore_
        description: |
          Prefix to the index names.
        validators: ignore_missing
        example: ds_res_
        required: false
      - key: ckanext.datastore_search.only_use_engine
        default: false
        type: bool
        description: |
          Only use the search engine, never inserting records into the database.
          Because the DataDictionary saves data types and field descriptions into
          the database column comments, the database table and fields will still
          be created to maintain this functionality.
        validators: ignore_missing boolean_validator
        required: false
      - key: ckanext.datastore_search.min_rows_for_index
        default: 100000
        type: int
        description: |
          Minimum database rows required for a search index to be created and used.
          Mutually exclusive with ckanext.datastore_search.only_use_engine
        validators: ignore_missing int_validator
        required: false
      - key: ckanext.datastore_search.redis.queue_name
        default: ckan_ds_create_index
        description: |
          Name of the REDIS queue.
        validators: ignore_missing
        example: ckan_ds_create_solr_core
        required: false
      - key: ckanext.datastore_search.redis.callback_queue_name
        default: ckan_ds_create_index_callback
        description: |
          Name of the REDIS queue for the callback queue.
        validators: ignore_missing
        example: ckan_ds_create_solr_core_callback
        required: false
      - key: ckanext.datastore_search.solr.configset
        default: datastore_resource
        description: |
          Name of the SOLR configset to use when creating new cores.
        validators: ignore_missing
        example: ckan_ds_resource
        required: false
      - key: ckanext.datastore_search.download_proxy_address
        default: None
        description: |
          NETLOC address for an internal proxy to download files.
          This is only used in XLoader & DataPusher integration when using ckanext.datastore_search.only_use_engine.
        validators: ignore_missing
        example: 127.0.0.1:5001
        required: false
      - key: ckanext.datastore_search.download_verify_https
        default: true
        type: bool
        description: |
          Whether or not to verify HTTPS to download files.
          This is only used in XLoader & DataPusher integration when using ckanext.datastore_search.only_use_engine.
        validators: ignore_missing boolean_validator
        example: false
        required: false
      - key: ckanext.datastore_search.always_reupload_file
        default: false
        type: bool
        description: |
          Whether or not to always ignore file hashes.
          This is only used in XLoader & DataPusher integration.
        validators: ignore_missing boolean_validator
        example: true
        required: false
